### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Normandy** [mono/xwt#1001]
https://github.com/mono/xwt/blob/4a5948bdb6d5f63cbc4d792367b7e8ff80ba1d70/Xwt.WPF/Xwt.WPFBackend.CellViews/CellViewBackend.cs#L52

I think this is a useless method, or you can answer, please, why do you need it?

**Comment by Therzok** [comment]
That method exists for extensibility purposes. In example, something could extend CellViewBackend and provide custom initialization logic.

In example, something actually _does_ use it, namely [TextCellViewBackend](https://github.com/mono/xwt/blob/af2540cb0b6a1c1e82c4f7ec8949565f6677e631/Xwt.WPF/Xwt.WPFBackend.CellViews/TextCellViewBackend.cs#L34)

**Comment by Therzok** [comment]
https://github.com/mono/xwt/blob/af2540cb0b6a1c1e82c4f7ec8949565f6677e631/Xwt.WPF/Xwt.WPFBackend.CellViews/CheckBoxCellViewBackend.csa

https://github.com/mono/xwt/blob/af2540cb0b6a1c1e82c4f7ec8949565f6677e631/Xwt.WPF/Xwt.WPFBackend.CellViews/RadioButtonCellViewBackend.cs

use it too
