### ISSUE TITLE
[Gtk] DialogButtons don't close dialog when they are clicked

### ISSUE THREAD

**Issue by knocte** [mono/xwt#104]
Sample code is (which works in WPF by the way):

	public class LoginWindow : Dialog
	{
		Label titleUserName = new Label("User Email:");
		Label titlePassword = new Label("Password:");

		TextEntry userName = new TextEntry();
		TextEntry password = new TextEntry();

		Table table = new Table();

		public LoginWindow()
		{
			table.Attach(titleUserName,0,0);
			table.Attach(userName, 1,0);

			table.Attach(titlePassword,0,1);
			table.Attach(password,1,1);

			Buttons.Add(new DialogButton(Command.Ok));
			Buttons.Add(new DialogButton(Command.Cancel));
			Content = table;
		}
	}

	public class App
	{
		public static void Run(string engineType)
		{
			Application.Initialize(engineType);

			var w = new LoginWindow();
			w.Title = "Lambda";
			w.Width = 300;
			w.Height = 100;
			w.Show();

			Application.Run();

			w.Dispose();
		}
	}

And the Gtk runner is:

	class MainClass
	{
		public static void Main(string[] args)
		{
			App.Run ("Xwt.GtkBackend.GtkEngine, Xwt.Gtk, Version=1.0.0.0");
		}
	}

**Comment by sevoku** [comment]
This can be closed.
