### ISSUE TITLE
TreeView does not worc on Cocoa

### ISSUE THREAD

**Issue by tomitrescak** [mono/xwt#152]
When running an example app on cocoa following exception occurs (I have localized the reason for exception down to TreeView):

2013-02-21 21:55:02.191 MacTest[56687:80f] -[Xwt.Mac.ScrollView invalidateIntrinsicContentSize]: unrecognized selector sent to instance 0x34624c0
2013-02-21 21:55:02.221 MacTest[56687:80f] An uncaught exception was raised
2013-02-21 21:55:02.222 MacTest[56687:80f] -[Xwt.Mac.ScrollView invalidateIntrinsicContentSize]: unrecognized selector sent to instance 0x34624c0
2013-02-21 21:55:02.223 MacTest[56687:80f] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Xwt.Mac.ScrollView invalidateIntrinsicContentSize]: unrecognized selector sent to instance 0x34624c0'
*** Call stack at first throw:
(
	0   CoreFoundation                      0x986476ca __raiseError + 410
	1   libobjc.A.dylib                     0x96eab5a9 objc_exception_throw + 56
	2   CoreFoundation                      0x9869490b -[NSObject(NSObject) doesNotRecognizeSelector:] + 187
	3   CoreFoundation                      0x985edc06 ___forwarding___ + 950
	4   CoreFoundation                      0x985ed7d2 _CF_forwarding_prep_0 + 50
	5   ???                                 0x02ee4e9c 0x0 + 49172124
	6   ???                                 0x042cbca4 0x0 + 70040740
	7   ???                                 0x042c82bb 0x0 + 70025915
	8   ???                                 0x042c7ff0 0x0 + 70025200
	9   ???                                 0x042c7ef4 0x0 + 70024948
	10  ???                                 0x042ac03a 0x0 + 69910586
	11  ???                                 0x042c74d0 0x0 + 70022352
	12  ???                                 0x02edabf8 0x0 + 49130488
	13  ???                                 0x02eda0a0 0x0 + 49127584
	14  ???                                 0x000a81d0 0x0 + 688592
	15  ???                                 0x000a7fe8 0x0 + 688104
	16  ???                                 0x000a813e 0x0 + 688446
	17  libmono-2.0.dylib                   0x0020c402 mono_jit_runtime_invoke + 722
	18  libmono-2.0.dylib                   0x003a7a7a mono_runtime_invoke + 170
	19  libmono-2.0.dylib                   0x003aa5f1 mono_runtime_exec_main + 705
	20  libmono-2.0.dylib                   0x003a9801 mono_runtime_run_main + 929
	21  libmono-2.0.dylib                   0x00269b95 mono_jit_exec + 149
	22  libmono-2.0.dylib                   0x0026c129 mono_main + 9609
	23  MacTest                             0x6fe544bf main + 3135
	24  MacTest                             0x6fe53875 start + 53
)

**Comment by sevoku** [comment]
I think we can close this. @tomitrescak: feel free to reopen the issue, and please add some more information about the system you are running (OS, Mono, Xamarin versions etc.)
