### ISSUE TITLE
[WPF] KeyPressed/KeyReleased events not working

### ISSUE THREAD

**Issue by aBothe** [mono/xwt#162]
Even after I found out that 
```csharp
var bk = Widget.GetWidgetBackend(this);
bk.EnableEvent(WidgetEvent.KeyPressed);
bk.EnableEvent(WidgetEvent.KeyReleased);
```
doesn't enable the triggering of local KeyPressed/KeyReleased overloads in my *Canvas* subclass, I'm kinda unsure about whether it's a bug or something is still missing in order to let me catch key events :-/

**Comment by sevoku** [comment]
It's like #301. It is not really an issue, since a Canvas can not get a focus initially. See #326 and the Drawing->TextInput example.
