### ISSUE TITLE
[Gtk] Widgets cannot have a transparent background

### ISSUE THREAD

**Issue by aBothe** [mono/xwt#173]
Perhaps not a major issue, but still a smaller annoyance because layout widgets like VBoxes drawn above a canvas are just messin the entire graphics up.

Hopefully it's just a XWT thing and not related to deeper code levels :-o

**Comment by sevoku** [comment]
Any update on this? Could we get some simple example code to reproduce this? I think the Canvas example does exactly this (putting boxes above canvas) and it seems to be working on all platforms even if the HBox is replaced by any other container (in https://github.com/mono/xwt/blob/master/TestApps/Samples/Samples/CanvasWithWidget.cs#L67).

**Comment by aBothe** [comment]
https://github.com/aBothe/GraphPlotter
I probably should've posted the code reference earlier :)

**Comment by sevoku** [comment]
Thanks! Have you tried the current master? I'll take a look later.

**Comment by aBothe** [comment]
Nope, haven't touched it for a rather long time, as you may see from the last commit's timestamp :)

**Comment by aBothe** [comment]
Just updated all dependencies and tested it again..it still shows a buggy rendering behaviour.

**Comment by aBothe** [comment]
Okay, I didn't set the background color for the canvas to Colors.White. 
Still, even when assigning Colors.Transparent to the side panels' backcolor properties, they're drawn white, not transparent.

**Comment by sevoku** [comment]
I see, you are using Gtk, which does not support transparent colors. Can you try Gtk3?

**Comment by aBothe** [comment]
Gonna get me all the dll's required for it first :)

**Comment by sevoku** [comment]
Ok, I've tried it with Gtk3 and this is how it looks like:
![graphplotter_038](https://cloud.githubusercontent.com/assets/951587/5792640/d98b8bee-9f22-11e4-9188-a2e20236a395.png)

There seem to be some little sizing issues with the buttons. Perhaps some Size Requests are needed in your code.

**Comment by sevoku** [comment]
So it looks like it is all about background color transparency which is not supported by Gtk2. In cases bg transparency is required, Gtk3 should be used. 

I've added a new issue for the ToolkitFeatures flags, where this Gtk2 limitation should be added.

**Comment by aBothe** [comment]
Nice then, thanks for your hint! :)
