### ISSUE TITLE
Support for a Browser widget

### ISSUE THREAD

**Issue by danfma** [mono/xwt#174]
If a browser widget is created based on awesomium (http://awesomium.codeplex.com/) or some other multiplatform embedded chrome library we could use this to create applications with web like interface.

**Comment by sevoku** [comment]
I think this can be closed. We have already a WebView (added in #278) which has been already improved over time and all backends have working native implementations.
I don't think we need an other "common" (not native) Xwt "only" implementation as part of Xwt. Something like that could be implemented as a separate (external) pure Xwt based project providing a common e.g WebKitWebView widget.
