### ISSUE TITLE
Question: How to implement b/w Bitmap

### ISSUE THREAD

**Issue by lytico** [mono/xwt#215]
I want to implement a black/white pixelformat.
in system.drawing, it is PixelFormat.Format1bppIndexed
in gtk, its Cairo.Format.A1
but how on mac? I didn't find any hints
has someone an ideay?
thanks!

**Comment by sevoku** [comment]
@lytico: did it work? 

Is it a "nice to have" feature for Xwt? Of so, we should add a new issue for proposals and deeper investigation. I close this until then.

**Comment by lytico** [comment]
No. It seems that OSX doesn't support 1 bit per pixel:
https://developer.apple.com/library/mac/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/dq_context/dq_context.html#//apple_ref/doc/uid/TP30001066-CH203-BCIBHHBB
