### ISSUE TITLE
[WPF] TreeView.ScrollToRow() and TreeView.SelectRow() do not work

### ISSUE THREAD

**Issue by dlech** [mono/xwt#235]
While working on a new sample, I added the following code to the end of the MainWindow() constructor of the Samples MainWindow class so that I did not have to manually select the sample that I was working on every time. Everything worked as expected in Gtk, but ```ScrollToRow (mn)``` and ```SelectRow (mn)``` do not work in WPF. 

````
Shown += (sender, e) =>
{
    samplesTree.ExpandToRow (mn);
    samplesTree.ScrollToRow (mn);
    samplesTree.SelectRow (mn);
};
````

Part of the problem was that on WPF, the Xwt Shown event is triggered by the WPF IsVisibleChanged event, which occurs before the window is actually fully loaded (WPF Loaded event). I fixed this [here](https://github.com/dlech/xwt/commit/fa72ce4afbe989e8f0f6bf6a9959cd2187983cc9). It got rid of some null reference exceptions, but did not fix the issue.

@ermau Looks like you wrote most of the backend for this. Any suggestions?

**Comment by sevoku** [comment]
Seems to be solved. Please reopen, if not.

**Comment by tsbarnes** [comment]
This is definitely still broken (or was re-broken at some point).  ScrollToRow isn't working on WPF currently.
