### ISSUE TITLE
Shouldn't Application.Initialize set a custom SynchronizationContext?

### ISSUE THREAD

**Issue by robinei** [mono/xwt#250]
When doing "await" on the main thread, one should expect to resume on the main thread as well. What happens now is that it resumes on the thread pool. Something like this?

<pre>
class XwtContext : SynchronizationContext {
    public override void Post(SendOrPostCallback d, Object state) {
        Application.Invoke(() => {
            d.Invoke(state);
        });
    }
    public override void Send(SendOrPostCallback d, Object state) {
        using (var ev = new ManualResetEvent(false)) {
            Application.Invoke(() => {
                d.Invoke(state);
                Thread.MemoryBarrier();
                ev.Set();
            });
            ev.WaitOne();
        }
    }
}
</pre>

**Comment by sevoku** [comment]
Done in #363 :smile:
