### ISSUE TITLE
WPF Box inside Frame somewhy don't apply VerticalAlign property

### ISSUE THREAD

**Issue by ksigne** [mono/xwt#263]
I'm trying to create such kind of UI:
<pre>
&lt;Frame MarginBottom="5" PaddingLeft="5" PaddingRight="5" Text="Визуализации"&gt;
                &lt;Box Orientation="Vertical" VAlign="Center"&gt;
                  &lt;Button Text="Поле температур"/&gt;
                  &lt;Button Text="Термограмма"/&gt;
                  &lt;Button Text="Термоасимметрия"/&gt;
                &lt;/Box&gt;
&lt;/Frame&gt;
</pre>

That's what i wanted (GTK is OK):
![image](https://f.cloud.github.com/assets/5941429/1561833/ccf029d0-503b-11e3-97ea-d6c16e0b0e72.png)
And that's what i get in WPF:
![image](https://f.cloud.github.com/assets/5941429/1561838/e52aa4da-503b-11e3-8c19-d2f32f17b933.png)

I tried some configurations like:
<pre>
&lt;Frame Text="123&gt;
&lt;Box Orientation="Horizontal" VAlign="Center"&gt;
&lt;Box Orientation="Vertical"&gt;
&lt;Button Text="Поле температур"/&gt;
&lt;Button Text="Термограмма"/&gt;
&lt;Button Text="Термоасимметрия"/&gt;
&lt;/Box&gt;
&lt;/Box&gt;
&lt;/Frame&gt;
</pre>
but didn't succeeded.

**Comment by sevoku** [comment]
seems to be fixed via 6b8cbd9bc9624c09b28d7d1aca24bba0bf492bbe. Please reopen if not.
