### ISSUE TITLE
WPF DrawTextLayout ignores text color

### ISSUE THREAD

**Issue by luiscubal** [mono/xwt#274]
TextLayout has a method `TextLayout.SetForeground(color, offset, length)` which is exactly what I need.
Unfortunately, this method is ignored on WPF and instead the color of `Xwt.Drawing.Context` is used.

I understand the usefulness of having a default color but, as it is, SetForeground is broken.
Removing `t.FormattedText.SetForegroundBrush (c.Brush);` from `ContextBackendHandler.cs` (line 257, project Xwt.WPF) fixes the issue, but removes the default color.

**Comment by sevoku** [comment]
fixed via #326
