### ISSUE TITLE
Wpf window spawns outside of the screen

### ISSUE THREAD

**Issue by MaikKlein** [mono/xwt#279]
I am using Windows 7 x64, Wpf and F# and the sample code spawns the window outside of my screen.

```
open System
open Xwt

[<STAThread>]
[<EntryPoint>]
let main argv = 
    Application.Initialize(ToolkitType.Wpf)
    let w = new Window (
               Title = "Xwt Demo Application",
               Width = 500.,
               Height = 500.,
               Location = Point(500.,500.)
    )
    w.Show()
    Application.Run()
```
It also completely ignores the height and width. As you can see I also tried the set the location manually but it also made no difference.

It seems to spawn somewhere around -100,-100

**Comment by sevoku** [comment]
fixed via #393
