### ISSUE TITLE
Xwt won't compile on Visual Studio 2010

### ISSUE THREAD

**Issue by hwthomas** [mono/xwt#292]
After the last commit (fe71a6ff33) Xwt.sln changed to
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 2012
and no longer loads into VS2010.  Changing back to Format Version 11.0 (VS2010) builds OK as far as I can tell.  Any reason not to go back?

**Comment by sevoku** [comment]
fixed via 4a51c50463a01d7e3357cd9b1fbee0444d8e8ad2? Please reopen if not.
