### ISSUE TITLE
[Mac] CanvasBackend  OnMouseEntered, Moved, Exited events not firing

### ISSUE THREAD

**Issue by hwthomas** [mono/xwt#297]
Canvas OnMouseEntered, OnMouseExited events do not fire on Mac Backend. 

OnMouseMoved starts to fire once a mouse button has been clicked inside the canvas, but then continues to fire even when the mouse is outside the Canvas Bounds, reporting X and Y positions relative to the Canvas origin (ie exceeding the Bounds).

I've done some preliminary investigation, but not managed to get anything working!  Does it need something like a TrackingArea defining?  I'll dig further if anyone can give me a few pointers, but I'm new to CoreGraphics.

**Comment by sevoku** [comment]
Any progress on this issue?

**Comment by sevoku** [comment]
I think this is fixed already. The events work for the Canvas in the Widget Events sample (https://github.com/mono/xwt/blob/master/TestApps/Samples/Samples/WidgetEvents.cs#L162).
