### ISSUE TITLE
[WPF] SeparatorMenuItem visibility

### ISSUE THREAD

**Issue by thiagoabreu** [mono/xwt#364]
The SeparatorMenuItem visibility property doesn't work on WPF because the in WPF the Separator is subclass of MenuItem and cannot be hidden.

Hide SeparatorMenuItem works on GTK. I don't know if it does on Mac.

**Comment by sevoku** [comment]
WPF fixed: f635c60d3363cac38d558dfefa0341c29ec04c92
MAC not affected.
