### ISSUE TITLE
GTK background color doesn't support transparency

### ISSUE THREAD

**Issue by bigpcz** [mono/xwt#386]
The following code makes custom widget background transparent in WPF backend but black in GTK backend on Windows platform.

	public class CustomWidget: Canvas
	{
		public CustomWidget()
		{
			this.BackgroundColor = Color.FromBytes(0, 0, 0, 0);
		}
	}

**Comment by sevoku** [comment]
Ok, I think we can close this one. I've added a new issue (#456), where this should be added to the ToolkitFeatures flags. We can add a new issue/PR in case there will be a new Gtk3 release for Windows.
