### ISSUE TITLE
Publish to nuget?

### ISSUE THREAD

**Issue by mitchelldm** [mono/xwt#444]
This would make it much easier to integrate.

**Comment by sevoku** [comment]
@slluis: any ideas about it, already? We should use some automated way I think. Could we use some infrastructure from the @mono team? Or AppVeyor maybe?. I saw @nathanaeljones has done this with AppVeyor and Travis-CI for your [Sharpen](https://github.com/slluis/sharpen) repository, maybe he could assist?

(for Gtk3 we could install the package from https://github.com/mono/gtk-sharp/releases in AppVeyor automatically, or publish a package for cinst (has gtk-sharp2 already: https://chocolatey.org/packages/gtksharp) and use cinst for the deps.)

Should I take a closer look on AppVeyor next days? And does the mono team have a NuGet account, which should be used, or do you have your own?

**Comment by sevoku** [comment]
After playing around with AppVeyor I was able to automatically build NuGet packages for Wpf and Gtk. If someone wants to give it a try: https://ci.appveyor.com/nuget/xwt-rh5gssg4yik5 (use it as NuGet repository), the builds can be found at: https://ci.appveyor.com/project/sevoku/xwt

**Comment by SirCmpwn** [comment]
:+1:

**Comment by dsuess** [comment]
any word on this?

**Comment by SirCmpwn** [comment]
Bump. (I am going to bump this whenever I need to install Xwt and it's still not on nuget).

**Comment by dsuess** [comment]
Hope you don't mind, i've been working on an Xwt NuGet package called, Xwt-Alt. It is currently being tested on NuGet's Integeration server before being ported over to the main site. All sources are 100% XWT, the only difference is the version number.  There will be a few different flavors to match each Xwt environment, starting with "Xwt-Alt for WPF" and "Xwt-Alt for Gtk".

The version number for Major  and Minor are the same. Build is incremented during "significant" changes to Xwt and Revision follows "yyddd" where "ddd" is the date based off of a 365 calendar year.

Example: v0.1.2.15333

https://int.nugettest.org/packages/Xwt-Alt.WPF/

**Comment by fuct** [comment]
Link update:
https://staging.nuget.org/packages/xwt-alt/

**Comment by lostmsu** [comment]
@dsuess, any update on this? I was going to start a new cross-platform desktop project, and wanted to use XWT as the UI framework. Can you advice for or against using it in a project, that will go to production in June - July?

**Comment by fuct** [comment]
You are correct @lostmsu, using the staging nuget server is acceptable. When the project is ready for the live server, it should seamlessly integrate over. Thank you for your interests on the project.

When choosing a proper cross-platform framework (Xwt vs Eto.Forms vs ...) it is entirely up to your own comfort level. We too had the moment of a fork in the road on what to use. Best advice, try out a few and see which one matches your features & coding styles.

**Comment by dsuess** [comment]
You are correct @lostmsu, using the Staging NuGet server is acceptable. When the project is ready for the live server, it should seamlessly integrate over. Thank you for your interests on the project. We should have it updated soon after the next round of testing.

When choosing a proper cross-platform UI framework (_Xwt vs Eto.Forms vs ..._) it is entirely up to your own comfort level. We too had the moment of a fork in the road on what to use. Best advice, try out a few and see which one matches your features & coding styles.

**Comment by listepo** [comment]
any update on this?

**Comment by aelij** [comment]
I've published a package with all the XWT assemblies (GTK, WPF, Mac) from the latest Xamarin Studio. If you'd like to take ownership of it, let me know.

**Comment by sevoku** [comment]
@aelij: Hey thanks, but you've included all backends in one. I've updated the nuspecs and the AppVeyor config to build and publish separate packages including Xwt.XamMac automatically: https://ci.appveyor.com/project/xwt/xwt-9wcqn. The PR is here: https://github.com/mono/xwt/pull/642, and you can find the temp. NuGet Feed here: https://ci.appveyor.com/nuget/xwt-msdh7kdbf2b7.

As soon as the PR is approved I'd like to publish automatic builds to NuGet directly, but I need to take ownership of the Package on NuGet. Can you add me with sevo@sevo.org?

**Comment by aelij** [comment]
@sevoku Done. Feel free to remove me from the package owners :)

**Comment by sevoku** [comment]
Thanks @aelij! I'll keep that configuration as it is for now until we merge the new nuspec files.

**Comment by sevoku** [comment]
[![Xwt](http://img.shields.io/nuget/v/Xwt.svg?style=flat)](https://www.nuget.org/packages/Xwt/)
Official Xwt packages are online!

Packages:
* [Xwt](https://www.nuget.org/packages/Xwt/)
* [Xwt.Gtk](https://www.nuget.org/packages/Xwt.Gtk/)
* [Xwt.Gtk.Mac](https://www.nuget.org/packages/Xwt.Gtk.Mac/)
* [Xwt.Gtk.Windows](https://www.nuget.org/packages/Xwt.Gtk.Windows/)
* [Xwt.Gtk3](https://www.nuget.org/packages/Xwt.Gtk3/)
* [Xwt.WPF](https://www.nuget.org/packages/Xwt.WPF/)
* [Xwt.XamMac](https://www.nuget.org/packages/Xwt.XamMac/)

AppVeyor Build:

[![Build status](https://ci.appveyor.com/api/projects/status/6k89wwx0a87gwesn/branch/master?svg=true)](https://ci.appveyor.com/project/xwt/xwt/branch/master)

We've published from `master` as stable `v0.2.*` until we do an API freeze and branch. Then we'll switch to a stable branch and publish from master with an experimental flag. Thats the plan for now.
