### ISSUE TITLE
[Gtk3] canvas not drawn inside scrolledwindow (sometimes)

### ISSUE THREAD

**Issue by sevoku** [mono/xwt#468]
When running the Gtk3 samples app, the ScrollableCanvas widget inside the ScrollWindowSample is not drawn. This does not occur when the last ScrollView is alone in the Box (removing the first three samples, leaving v4 only).

**Comment by hwthomas** [comment]
That was my experience also (and as far as I'd got into tracking it down).  Since the Gtk3 *OnDrawn* is never called, I'm suspecting that it is a layout issue, and that the ScrollView is not getting any window space/exposure.  However, I've not yet been able to investigate further.

**Comment by sevoku** [comment]
Ok, I was able to narrow it down to a Gtk.Viewport issue with property reregistration. I'll revert my change in 76ee7a108cf894e43ab9e3d60245166f9a7eddb7 and add a custom Gtk.Bin implementing Gtk.IScrollableImplementor for Gtk3. This seems to solve the issue.
