### ISSUE TITLE
Gtk Treeview Image are aligned Top instead of Center

### ISSUE THREAD

**Issue by cra0zy** [mono/xwt#525]
It looks so unnatural for the treeview icon to be aligned up, it especially becomes visible if the icon is smaller.

Gtk 2 / 3 aligned icons Top
Wpf / Mac aligned icons Center

#433 already has the images, just look in it to see the comparison between Gtk and WPF / Mac.

Example app is more than enough to notice it:
![image](https://cloud.githubusercontent.com/assets/6773302/8461471/218d3024-202d-11e5-8dc4-c9bcfaeb98cb.png)

**Comment by sevoku** [comment]
What we need is a cell alignment implementation, not only for image cell views.

**Comment by cra0zy** [comment]
This has been fixed, so closing...
