### ISSUE TITLE
Use Protobuild to manage cross-platform projects

### ISSUE THREAD

**Issue by hach-que** [mono/xwt#555]
[Protobuild](http://protobuild.org/) is a project generator and package manager for cross-platform C# and C++ projects.  It handles generating C# project files for a given target platform, and can be used to produce and publish cross-platform packages with very few commands.

In particular, some of the main features of Protobuild are:
- Projects can be excluded from generation based on the target platform: **[example](https://github.com/mono/MonoGame/blob/develop/Build/Projects/2MGFX.definition#L2)**
- Project definition files are cleaner and focus only on the important information (references, files and non-default properties).  For example, this definition file is much easier to read than the equivalent C# project: **[example](https://github.com/mono/MonoGame/blob/develop/Build/Projects/2MGFX.definition)**
- External project definitions in Protobulid allow you to group and change external references based on the target platform.  You can add references to the GAC, binaries in the repository, external C# projects and more based on the target platform.  **[example](https://github.com/mono/MonoGame/blob/develop/Build/Projects/FrameworkReferences.definition)**
- For Mac OS X, Protobuild automatically handles referencing MonoMac / XamMac based on what is licensed.

It has been used quite successfully by MonoGame to significantly reduce the amount of project configuration required, and to simplify the management of external dependencies.  To see MonoGame's migration to Protobuild (and the discussion of it), I recommend reading these links: https://github.com/mono/MonoGame/issues/1722#issuecomment-19533271, https://github.com/mono/MonoGame/pull/1945, https://github.com/mono/MonoGame/pull/2249.

Once a project uses Protobuild, users only need to double-click the Protobuild executable (if they are on Windows), or run `mono Protobuild.exe` from a terminal to generate the C# project and solution files.  These files will work for both command-line build tools on that platform, as well as the native IDEs (Visual Studio / Xamarin Studio / MonoDevelop).  The C# project and solution files are not included in the repository after migrating to Protobuild.

Protobuild can also automatically produce binary packages for a project for a given target platform, with zero configuration required by the developers.  This is because Protobuild understands the project structure, and can correctly include both the binaries produced by a project, and all of the dependencies it has (including dependencies on external binaries and other projects).  For example, to produce a package for Linux after building the solution, you (or a build server) would run `Protobuild.exe --pack . Linux.tar.lzma Linux`.  This package system is (unlike NuGet) truly cross-platform and supports projects which use P/Invoke and platform-specific binaries.

**Comment by sevoku** [comment]
This is not on roadmap.
