### ISSUE TITLE
Project version schema is not being applied

### ISSUE THREAD

**Issue by dsuess** [mono/xwt#564]
**Enhancement:**
Please use a proper version schema rule. Currently the project has been at version 0.1.0.0 for ages, yet significant bug fixes have been applied.

**Solves:**
As a software developer there is a strong need to an internal incremental system and use of version control Tags. The lack thereof makes it difficult to track enhancements and which .DLL is up to date.

As a product owner, without a system in place, this would be very difficult to track my team members' progress and ability to deliver our product to our customers - promising them changes.

_I know this is minor. Thank you & keep up the great work!_

**Comment by sevoku** [comment]
We bump the version/build number in the NuGet packages now. I think there is no need to bump it in the sources for each commit in the repo.
