### ISSUE TITLE
Mac: Better small PopupContextMenu handling

### ISSUE THREAD

**Issue by vancura** [mono/xwt#569]
Currently we have small `PopupContextMenu` on Mac, and it would be better to have an API to select the font size (I guess standard or small, there's no reason to allow any font size value).

Here's my old patch from last year: https://github.com/mono/xwt/commit/4e54e814eff07ca09646b387f16ee96d1dbfecc3

Thanks,
V.

**Comment by sevoku** [comment]
I've added a complete `Menu.Font` implementation in #572, since it doesn't make sense to modify just the size. To change the font size of a menu one can do: ```Menu.Font = Menu.Font.WithSize (20);```

@Therzok: can you review?

**Comment by Therzok** [comment]
Reviewing.
