### ISSUE TITLE
[Xwt.GtkBackend] ImageHandler.cs doesn't compile for Gtk3

### ISSUE THREAD

**Issue by hwthomas** [mono/xwt#584]
Using MonoDevelop 5.10.1, with included package gdk-sharp-3.0 2.99.3, ImageHandler.cs fails at line 196 (Gdk.Pixmap pmap ...) since  Gdk.Pixmap no longer exists.  The code in ImageHandler hasn't changed since July 2015, so I presume it is gdk-sharp which has dropped Pixmap since then (when it presumably compiled).

Has anyone else noticed this?

**Comment by sevoku** [comment]
Build fixed. The change comes from the `image-loader` branch that has been merged recently. The code failing for Gtk3 should draw a missing image in case Gtk can not load a specific stock icon. I simply disabled that part for Gtk3 for now, but we may need a Gtk3 impl. for that case too. I added a `TODO` comment. Actually this shouldn't be an issue on Linux, cause the default stock icons are always installed and loadable.

Thanks for reporting this!

**Comment by hwthomas** [comment]
I've had a go at fixing this as per the Gtk3 porting guide re Pixmaps.  Creating a Cairo.ImageSurface and drawing the 'missing icon' is straightforward, but I can't seem to find the Gdk# equivalent of Gdk.pixbuf_get_from_surface (surface, x, y, w, h) in order to return a Pixbuf.  Any hints please?

**Comment by sevoku** [comment]
Yes GtkSharp is missing the wrapper for `pixbuf_get_from_surface`. But you can try something like this:
```c#
#if XWT_GTK3
[DllImport (GtkInterop.LIBGDK, CallingConvention = CallingConvention.Cdecl)]
static extern IntPtr gdk_pixbuf_get_from_surface (IntPtr surface, int src_x, int src_y, int width, int height);

public static Gdk.Pixbuf GetFromSurface (Cairo.Surface surface, int src_x, int src_y, int width, int height)
{
	IntPtr raw_ret = gdk_pixbuf_get_from_surface (surface.Handle, src_x, src_y, width, height);
	Gdk.Pixbuf ret;
	if (raw_ret == IntPtr.Zero)
		ret = null;
	else
		ret = (Gdk.Pixbuf)GLib.Object.GetObject (raw_ret);
	return ret;
}
#endif
```
You can drop it into `ImageHandler.cs` directly, or (even better) here: https://github.com/mono/xwt/blob/master/Xwt.Gtk/Xwt.GtkBackend/Gtk3Extensions.cs#L64 with an extension sig:
```c#
public static Gdk.Pixbuf ToPixbuf (this Cairo.Surface surface, int src_x, int src_y, int width, int height)
{ ... }
```
(without the `#if XWT_GTK3` then)

**Comment by hwthomas** [comment]
Thanks.  I'll add that to the Gtk3Extensions and submit a pull request 
when I've tested the new 'MissingIcon' drawing.

**Comment by hwthomas** [comment]
Tests completed, and new Pull request submitted as discussed.
