### ISSUE TITLE
Intelligently choose the best available GTK version

### ISSUE THREAD

**Issue by SirCmpwn** [mono/xwt#591]
Maybe through something like ToolkitType.Auto, which would pick the most appropriate backend for the platform. Currently I have a try...catch that attempts Gtk3 first and then goes for Gtk if that throws an exception, but this causes issues later on in the application.

**Comment by sevoku** [comment]
You can use `Application.Initialize ()` (without params) and it will try load all backends until one succeeds. See https://github.com/mono/xwt/blob/master/Xwt/Xwt/Toolkit.cs#L49 and https://github.com/mono/xwt/blob/master/Xwt/Xwt/Toolkit.cs#L171.

**Comment by SirCmpwn** [comment]
Thanks!
