### ISSUE TITLE
[gtk] webviewbackend is not propagating sizechanged back to webview

### ISSUE THREAD

**Issue by lytico** [mono/xwt#604]
testcase:
run GtkTest
navigate to Widgets.WebView
press Load SampleHtml

result:

![xwt demo application_webview-1](https://cloud.githubusercontent.com/assets/1479980/16474969/0f8db412-3e7b-11e6-9f44-a961c4d6c922.png)

then:

maximize window
minimize window

result:

webview size remains the size got by maximizing the window

![xwt demo application_webview-2](https://cloud.githubusercontent.com/assets/1479980/16474968/0f8bdda4-3e7b-11e6-9d60-9536faeb87c8.png)

possible solution:
implement 
http://webkitgtk.org/reference/webkitgtk/stable/WebKitWebWindowFeatures.html
in Xwt.GtkBackend.WebKit.WebView

**Comment by sevoku** [comment]
I've fixed the issue partially in #614, but there is still a small issue with the horizontal scroll bar.
