### ISSUE TITLE
WPF chromium container

### ISSUE THREAD

**Issue by Kallzz** [mono/xwt#632]
Hi, how can i host webpages within GWT WPF in windows  and MAC?

**Comment by sevoku** [comment]
There is no Chromium based backend, but you can use the `Xwt.WebView` widget to host web pages using IE on Windows or WebKit on Linux/Mac.
I don't think that we'll implement a cross-platform Chromium backend for WebView. This can be done in a separate extension project (replacing existing engine implementations).
