### ISSUE TITLE
how to get rid of console window?

### ISSUE THREAD

**Issue by joreg** [mono/xwt#680]
helos,

the docs say: "...create an empty .NET project in your favorite language..." and then do:

    Application.Initialize (ToolkitType.Wpf);

when doing so on windows, this basically works fine only that next to the main gui-window i also get a console window which i have not asked for. is there a simple way to get rid of it?

**Comment by RayKoopa** [comment]
Right click your project in the Solution Explorer > Properties > Set **Output type** to "Windows Application".

**Comment by joreg** [comment]
@RayKoopa indeed, thanks! i had tried that before and it didn't work because apparently i forgot to rebuild...
