### ISSUE TITLE
xwt window.dispose doesn't work because it can not exit. 

### ISSUE THREAD

**Issue by sourceskyboxer** [mono/xwt#689]
If I test from Visual Studio 2017 Community than I see after exiting window and Visual Studio shows "running" why -> That is why your xwt.window can't quit. I need stop "running" than I try again.
Not working.....

If I try method of closed += new EventHandler(closedHandler);
and method for closedHandler -> try exit of application and nothing.

Wow. I thought any people say Xwt Frameworks are best. But for me. No! I am not stupid.
PS: Why not use wxWidgets and it has same Mac, Linux, Windows, iOS and Android now
I find so sad because wxWidgets for C# is stopped to development.
I wish your xwt framework is same good. like Gtk or QT or native of current operating system.

My code:
```
using System;
using Xwt;

namespace Painter
{
    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            Application.Initialize(ToolkitType.Gtk);
            var mainWindow = new Window()
            {
                Title = "Xwt Demo Application",
                Width = 500,
                Height = 400
            };
            mainWindow.Show();
            Application.Run();
            mainWindow.Closed += (object sender, EventArgs e) =>
            {
                mainWindow.Close();
                mainWindow.Dispose();
                Application.Exit();
            };
        }
    }
}
```
And it doesn't work :(

**Comment by sevoku** [comment]
`Application.Run()` blocks until `Application.Exit ()` is called. Hence you need to set up everything before the application starts like this:
```
mainWindow.Closed += (sender, e) =>
{
    Application.Exit();
};
mainWindow.Show();
Application.Run();
mainWindow.Dispose();
Application.Dispose();
```
I'd recommend to look into the examples App here: https://github.com/mono/xwt/blob/master/TestApps/Samples/App.cs and https://github.com/mono/xwt/blob/master/TestApps/Samples/MainWindow.cs#L163

**Comment by sourceskyboxer** [comment]
Thanks for fixed points.

I have improved for external cs like gtk# Program.cs and MainWindow.cs.

It is good result:
```
using System;
using Xwt;
namespace Painter
{
    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            Application.Initialize(ToolkitType.Gtk);
            MainWindow myWin = new MainWindow();
        }
    }
}
```
```
using Xwt;

namespace Painter
{
    class MainWindow : Window
    {
        public MainWindow()
        {
            Title = "Xwt Demo Application";
            Width = 500;
            Height = 400;
            Closed += (sender, e) =>
            {
                Application.Exit();
            };
            Show();
            Application.Run();
            Dispose();
            Application.Dispose();
        }
    }
}
```
Thanks for understanding and improving!

**Comment by sourceskyboxer** [comment]
Hello dear, 

I have bug because RichTextEditor gets error because it looks like at ...

```
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xwt.GtkBackend.RichTextViewBackend.GtkTextView.UpdateLinkColor()
   at Xwt.GtkBackend.RichTextViewBackend.GtkTextView.OnRealized()
   at Gtk.Widget.realized_cb(IntPtr widget)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at Gtk.Widget.realized_cb(IntPtr widget)
   at GLib.Object.g_object_set_property(IntPtr obj, IntPtr name, Value& val)
   at GLib.Object.SetProperty(String name, Value val)
   at Gtk.Widget.set_Visible(Boolean value)
   at Xwt.GtkBackend.WindowFrameBackend.Xwt.Backends.IWindowFrameBackend.set_Visible(Boolean value)
   at Xwt.WindowFrame.Show()
   at Painter.Program.Main(String[] args) in c:\users\jens\documents\visual studio 2017\Projects\Painter\Painter\Program.cs:line 30

The program '[14968] Painter.exe' has exited with code 1 (0x1).
```

What does it mean?
How do I fix? Thanks!

**Comment by sevoku** [comment]
Looks like a bug, but I'm not sure what could be `null` in `Xwt.GtkBackend.RichTextViewBackend.GtkTextView.UpdateLinkColor()`.
Could you clone current master and build your app with it in debug mode? The exception should give us an exact line number.

**Comment by sevoku** [comment]
Oh, maybe ... did you set any text before showing the Windows? Try to init the TextView with an empty string. If it works, then I think I know what it is.

**Comment by sevoku** [comment]
Nevermind, found it, it a bug. Just call `textview.LoadText (string.Empty, new Xwt.Formats.PlainTextFormat ());` right after `new RichTextView ()`. Or use the text you want to show instead of string.Empty. Its just important that you set some content before you call `Window.Show()`.

**Comment by sourceskyboxer** [comment]
Thanks for solution but I type TextView but it looks like  empty text. I forget to editable is true or what do I should understand? Thanks for help! Tomorrow  I try again.

**Comment by sevoku** [comment]
RichTextView is read only to show formatted (selectable) text. `TextEntry` allows input.

**Comment by sourceskyboxer** [comment]
Thanks for explanation! 

I am happy because I suggest with winforms via Application.Invoke()

Example: OpenFileDialog from System.Windows.Forms:
```
            FileOpenMenuItem.Clicked += (o, e) => {
                // Support WiNForm with Xwt = Windows 10 and 8, 7 :)
                Xwt.Application.Invoke(delegate
                {
                    System.Windows.Forms.OpenFileDialog fileDialog = new System.Windows.Forms.OpenFileDialog();
                    fileDialog.Title = "Open text";
                    fileDialog.Filter = "Text files ( *.txt ) | *.txt";
                    System.Windows.Forms.DialogResult result = fileDialog.ShowDialog();
                    if(result == System.Windows.Forms.DialogResult.OK)
                    {
                        TextView.LoadFile(fileDialog.FileName, Xwt.Formats.TextFormat.Markdown);
                    }
                });
            };
```
![xwt_winforms_01_ofd](https://cloud.githubusercontent.com/assets/3496136/26284236/eaa1ab74-3e36-11e7-8c57-4d470cd4ee9e.JPG)

Or MessageBox from winforms too
```
HelpAbout.Clicked += (o, e) =>
            {
                 Xwt.Application.Invoke(delegate
                {
                    System.Windows.Forms.MessageBox.Show("About Xwt Application 1.0.0", "About", System.Windows.Forms.MessageBoxButtons.OK);
                });
            };
```
![xwt_winforms_01_messagebox](https://cloud.githubusercontent.com/assets/3496136/26284260/603e61e2-3e37-11e7-8183-bcbf8fed90fd.JPG)

That is great! :) Thanks for help! Now I can continue.... Can I add OpenGL.net 0.4.2 to Xwt If not than I need Application.Invoke() ?

**Comment by Therzok** [comment]
Why do you need to use WinForms? There is an OpenFileDialog defined in Xwt:
https://github.com/mono/xwt/blob/master/Xwt/Xwt/OpenFileDialog.cs#L32

**Comment by sourceskyboxer** [comment]
No OpenFileDialog from Xwt sees like GTK OpenFileDialog. That is why I use Winforms-OpenFileDialog
![xwt_openfiledialog_from_gtksharp](https://cloud.githubusercontent.com/assets/3496136/26284772/1121a0c2-3e43-11e7-9486-afbe0dfdfc92.JPG)

But I define for winforms-Openfiledialog like folders are yellow and computer or drives are original from Windows 10. not Linux-Type!

**Comment by Therzok** [comment]
That's because you're initializing the toolkit as Gtk, and not enabling the WPF toolkit so the native Windows dialog is used.

If you reference the Xwt.WPF dll and copy it to the output directory, then you can use `Toolkit.NativeEngine.Invoke` and you'll get the native windows file dialog.

**Comment by sourceskyboxer** [comment]
Yes But It looks common with black middle toolbox like WPF Format. It cannot remove because I am using Windows 10. I don't like that. Thanks for good suggestion. I would like to use normal winforms. Don't worry! My decision says winforms.
