### ISSUE TITLE
Screenshot, Examples

### ISSUE THREAD

**Issue by mika76** [mono/xwt#750]
A UI library/toolkit without a single screenshot?!

**Comment by XeonG** [comment]
my thoughts exactly.. onto the next tab then

**Comment by HinTak** [comment]
There is a master example which demonstrates all the widgets. It is not hard to make some screenshot yourself.

**Comment by sevoku** [comment]
This is not an engine but a toolkit which uses native engines, so the applications written in Xwt look and behave like any other native application. Therefore I don't see a reason why we should add screenshots of Xwt examples which would look like any other application on any of the supported platforms. Just run any native WPF, Cocoa, Gtk application to see how it would look like.

Also please find a bunch of examples in https://github.com/mono/xwt/tree/master/TestApps/Samples.

**Comment by mika76** [comment]
Look, I meant no disrespect - running an open source project is hard work - but marketing it is necessary and the way it's currently marketed is not great. 

Why would I want to use up my valuable time and effort to download some library just to see what it looks like? Making newcomers _have_ to download something and struggle with building and such just to see a screenshot that anyone who is already involved with the project could have uploaded is not a great message to send.

You say it's just using native controls, but I for one doubt that's true in 100% of the cases (there is no native calendar control in Windows as far as I know for example), and even so there are a million ways to make it look good or bad. 

A screenshot or two would go a long way. But all your answers have told me is that you guys are not very confident in this library/engine/toolkit or that you just could not be bothered. Either way is not great marketing.

**Comment by dustinlacewell** [comment]
Still no screenshot. This issue is what comes up when you search "xwt screenshot" :joy:

**Comment by mkschreder** [comment]
Well, still no screenshots
