### ISSUE TITLE
[XamMac] Truncated items in ListBox on High Sierra when adding after initial display

### ISSUE THREAD

**Issue by xecrets** [mono/xwt#765]
Creating a ListBox, adding items and displaying works fine. Adding items after initial display causes longer items to be visually truncated to the length of the shortest item in the list at the time. For example removing all items, and then adding an item causes it to be truncated completely.

A complete sample application demonstrating the behavior is included, build with Visual Studio 2017 and run on macOS High Sierra. A not-very-tasteful workaround is also included.

Built and run with Xwt 0.2.60

[ListBoxHighSierra.zip](https://github.com/mono/xwt/files/1556745/ListBoxHighSierra.zip)

**Comment by sevoku** [comment]
Thanks for reporting. I forgot to remove the deprecated sizing code there.
