### ISSUE TITLE
[Feature Request] Add ability to disable a control

### ISSUE THREAD

**Issue by dansiegel** [mono/xwt#771]
A common task in UI development is to disable a control based on user interaction. For instance a user unchecks a CheckBox and a TextEntry or ComboBox is disable. Currently the only way I can see to handle this in Xwt is to set the Visible property to false which causes a layout update. It would be better if there was a Disable property so that the control remains visible but not editable.

**Comment by slluis** [comment]
That's the Sensitive property.
