### ISSUE TITLE
TestApps/Samples/Samples/TreeViewEvents.cs

### ISSUE THREAD

**Issue by elsupergomez** [mono/xwt#790]
The example use code convention supported only in C# 7 in lines 105, 205 and 232.
I use mono 4.8 (last package available for Fedora and CentOS) that not has full support for C#7 but has for C# 6.

I suggest use C# 6 standard.
Thanks

**Comment by sevoku** [comment]
Oh, yes, that needs to be fixed

**Comment by elsupergomez** [comment]
Thanks.
It work ok now.
