### ISSUE TITLE
Provide a way to determine if the dialog was cancelled in the FileSelector and FolderSelector

### ISSUE THREAD

**Issue by mrward** [mono/xwt#817]
The current behaviour of the FileSelector is that if the user browses to a different folder, then cancels the dialog, then next time the FileSelector is opened the folder browsed to is selected. Since there is no event fired that indicates that the dialog was cancelled it does not seem to be possible to reset the CurrentFolder property.

Ideas:
  Add a Canceled event.
  Add a `PreserveFolder` property.
  Add a BeforeBrowse event - fired before the dialog is opened.

**Comment by stoiandan** [comment]
I'd like to take this. But I'm new here, will first need to setup my env, and get things working :)
So add a Canceled event in the FileSelector class?

**Comment by mrward** [comment]
The original problem I had resulted in a workaround being added to [monodevelop](https://github.com/mono/monodevelop/commit/4d5934387c35353253bd9e1889c65156d3a83f27#diff-145c6fb4c19a4d10666d2151593b8a4e) since the XWT FileSelector did not work quite the same as the Gtk one available from MonoDevelop.Components.

The FileSelector has a FileChanged event but there is no way to know if the dialog was cancelled.

Another idea would be to have a Canceled property on the FileSelector instead of an event.

**Comment by sevoku** [comment]
I'd prefer events with `WidgetEventArgs`:

**`event EventHandler<WidgetEventArgs> Browse`**
* fired before browse, can be overridden/suppressed by `WidgetEventArgs.Handled`
* let's call it `Browse` to follow the Xwt event naming pattern without prefixes (with virtual `OnBrowse()`)

**`event EventHandler<SelectorDialogClosedEventArgs> SelectorClosed`**
* fired after the dialog has been closed
* update `FileSelector.FilePath` and `FileSelector.CurrentFolder` only if not `SelectorDialogClosedEventArgs.Handled`

With the following EventArgs:
```c#
public class SelectorDialogClosedEventArgs : WidgetEventArgs
{
	// true if canceled
	public bool Canceled { get; }
}

public class FileSelectorDialogClosedEventArgs : SelectorDialogClosedEventArgs
{
	// picked folder
	public string SelectedFolder { get; }

	// picked path (absolute, inside picked folder)
	public string SelectedFilePath { get; }
}
```
This would allow us to add the same `Canceled` functionality to other selectors (FontSelector, ColorSelector, etc. + a common selector interface) later.

**Comment by slluis** [comment]
Do we really needs this additional api? This looks like a bug to me. We can just fix the implementation so that CurrentFolder is not updated if the file dialog is cancelled.

**Comment by sevoku** [comment]
@slluis right, I think it's because the dialog instance is being reused and `CurrentFolder` is mapped to it, if it exists. However that new API is also useful.

**Comment by Therzok** [comment]
Orthogonally, Canceled API is indeed useful. In case we don't, it would just need to run the finally code only if `true` was returned by `IFileDialogBackend.Run`
https://github.com/mono/xwt/blob/df16ea5318e15c23c10645f472297bbb95f4b43f/Xwt/Xwt/FileSelector.cs#L281

**Comment by Therzok** [comment]
Huh, we don't seem to signal OK/Cancel anywhere in the Chooser.

**Comment by sevoku** [comment]
yeah, the File dialogs need some changes too to support his. And I remember some Gtk API limitations when I looked into this some time ago, but I don't remember where exactly.

**Comment by stoiandan** [comment]
@slluis  @sevoku @Therzok 
I've looked a bit more into it, and it looks to me like the propery/event should be put in [FileDialog ](https://github.com/mono/xwt/blob/af2540cb0b6a1c1e82c4f7ec8949565f6677e631/Xwt/Xwt/FileDialog.cs)and not [FileSelector](https://github.com/mono/xwt/blob/f073f52c6acfeea09f80de629d373d7681ed7ec0/Xwt/Xwt/FileSelector.cs)

**Comment by Therzok** [comment]
`PreserveFolder` could be used by the consumers to set whether the CurrentFolder would be stored or not.

**Comment by stoiandan** [comment]
@Therzok I've tested with WpfTest on Windows, If I cancel the dialog, then:
https://github.com/mono/xwt/blob/af2540cb0b6a1c1e82c4f7ec8949565f6677e631/Xwt/Xwt/FileDialog.cs#L191
Will be empty, so there is nothing to store.

**Comment by slluis** [comment]
Even if those events may be useful, 1) we don't need them, 2) it may not be possible to implement them in all platforms. This is a bug that can be fixed with a 1-line change.

**Comment by stoiandan** [comment]
Done a PR: https://github.com/mono/xwt/pull/905

**Comment by stoiandan** [comment]
@slluis 
Maybe I've gotten it wrong and did a non-sense, what do you think about the PR?
